@host =192.168.225.106:7001

##########################===公告===##############################
GET http://{{host}}/api/v1/agentmessages HTTP/1.1

# 返回结果
# {
#   "code": 0,
#   "msg": "ok",
#   "data": [
#     {
#       "_id": "5a5c68b0c166c7dba2d4c5e7",
#       "updatedAt": "2018-01-15T08:39:12.904Z", 
#       "createdAt": "2018-01-15T08:39:12.904Z", #数据创建时间
#       "__v": 0,
#       "deleted": false,           
#       "content": "全服发钱了快快领取"          #公告内容
#     },
#     {
#       "_id": "5a5c68b0c166c7dba2d4c5e6",
#       "updatedAt": "2018-01-15T08:39:12.903Z",
#       "createdAt": "2018-01-15T08:39:12.903Z",
#       "__v": 0,
#       "deleted": false,
#       "content": "全服发钱了快快领取"
#     }
#   ]
# }