@host =192.168.225.106:7001

##########################===邮件列表===##############################
#参数
#limit
#page

GET http://{{host}}/api/v1/agentmails?limit=2&page=1 HTTP/1.1

# 返回结果
# {
#   "code": 200,
#   "msg": "ok",
#   "errorCode": 0,
#   "data": {
#     "list": [
#       {
#         "_id": "5a59c22573b99e54a4757cea",
#         "createdAt": "2018-01-13T10:50:43.334Z", #数据创建日期
#    iI:     "content": "阿斯顿发生打法是否",   #正文内容
#         "title": "你好"                 #标题
#       },
#       {
#         "_id": "5a59c23173b99e54a4757ceb",
#         "createdAt": "2018-01-13T10:51:57.195Z",
#         "content": "阿斯顿发生打法是否",
#         "title": "你好"
#       }
#     ],
#     "count": 5, #数据总量
#     "time": "2018-01-15 02:18:46"
#   }
# }